sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: dehesan-sky
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDuDYMeBqnEKfhx3PTf
    access-key-secret: TQtFSZwzOouucWY4bRo6dHqCwhnEZ0
  redis:
    host: localhost
    port: 6379
    database: 1